name: Github Release Created

on:
  release:
    types: ["published"] # Inherits all input defaults

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to int in Dev AWS Account
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        component: [reporting]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0

      - name: Updating Main Environment
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        run: |
          bash .github/scripts/dispatch_internal_repo_workflow.sh \
            --releaseVersion "${{ github.event.release.tag_name }}" \
            --targetWorkflow "dispatch-deploy-static-notify-reporting-env.yaml" \
            --targetEnvironment "int" \
            --targetAccountGroup "nhs-notify-reporting-dev" \
            --targetComponent "${{ matrix.component }}" \
            --terraformAction "apply"
